import MainLayout from "@/components/layouts/MainLayout";
import ThemeSwitch from "@/components/widgets/ThemeSwitch";
import { AuthProvider } from "@/libs/providers/auth";
import MyThemeProvider from "@/libs/providers/themes";
import "@/styles/globals.css";
import { Metadata } from "next";
import { Poppins } from "next/font/google";

// const roboto = Roboto({ subsets: ["latin"], weight: "400" });
const poppins = Poppins({ subsets: ["latin"], weight: "400" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  viewport: "width=device-width, initial-scale=1.0",
};
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <MyThemeProvider>
          <AuthProvider>
            <div className="fixed top-1/2 right-4 z-50 hidden xl:block">
              <ThemeSwitch />
            </div>
            {children}
          </AuthProvider>
        </MyThemeProvider>
      </body>
    </html>
  );
}
